apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-access-slack-sa
  namespace: eks-access-slack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-access-slack-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["eksaccessrequests"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["eksaccessrequests/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["eksaccessrequests/finalizers"]
  verbs: ["update"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["approvalpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["approvalpolicies/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["approvalpolicies/finalizers"]
  verbs: ["update"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["awsaccounts"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["awsaccounts/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["eksclusters"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["eksclusters/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["iamroles"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["access.eksaccess.io"]
  resources: ["iamroles/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-access-slack-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-access-slack-role
subjects:
- kind: ServiceAccount
  name: eks-access-slack-sa
  namespace: eks-access-slack
