apiVersion: v1
kind: Service
metadata:
  name: eks-access-slack-service
  namespace: eks-access-slack
  labels:
    app: eks-access-slack
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: health
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: webhook
  - port: 9443
    targetPort: 9443
    protocol: TCP
    name: webhook-secure
  selector:
    app: eks-access-slack
