# This rule is not used by the project controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants edit permissions over access.eksaccess.io.
# This role is intended for users authorized to modify IAMRole resources,
# but not to delete them or modify their status.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: iamrole-editor-role
rules:
- apiGroups:
  - access.eksaccess.io
  resources:
  - iamroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.eksaccess.io
  resources:
  - iamroles/status
  verbs:
  - get
