# This rule is not used by the project controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only permissions over access.eksaccess.io.
# This role is intended for users authorized to view IAMRole resources,
# but not to modify them.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: iamrole-viewer-role
rules:
- apiGroups:
  - access.eksaccess.io
  resources:
  - iamroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - access.eksaccess.io
  resources:
  - iamroles/status
  verbs:
  - get
