---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - access.eksaccess.io
  resources:
  - approvalpolicies
  - eksaccessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.eksaccess.io
  resources:
  - approvalpolicies/finalizers
  - eksaccessrequests/finalizers
  verbs:
  - update
- apiGroups:
  - access.eksaccess.io
  resources:
  - approvalpolicies/status
  - awsaccounts/status
  - eksaccessrequests/status
  - eksclusters/status
  - iamroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - access.eksaccess.io
  resources:
  - awsaccounts
  - eksclusters
  - iamroles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
